# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\Dev\ppython\GUI\QtDesigner\once.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(401, 304)
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 401, 300))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.comboBox = QtWidgets.QComboBox(self.tab)
        self.comboBox.setGeometry(QtCore.QRect(130, 20, 141, 22))
        self.comboBox.setEditable(True)
        self.comboBox.setCurrentText("")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.btn = QtWidgets.QPushButton(self.tab)
        self.btn.setGeometry(QtCore.QRect(70, 90, 75, 23))
        self.btn.setObjectName("btn")
        self.alert = QtWidgets.QPushButton(self.tab)
        self.alert.setGeometry(QtCore.QRect(210, 90, 71, 23))
        self.alert.setObjectName("alert")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        self.comboBox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "演示窗口"))
        self.comboBox.setPlaceholderText(_translate("Form", "请选择"))
        self.comboBox.setItemText(0, _translate("Form", "新建项目1"))
        self.comboBox.setItemText(1, _translate("Form", "新建项目2"))
        self.comboBox.setItemText(2, _translate("Form", "新建项目3"))
        self.btn.setText(_translate("Form", "按钮"))
        self.alert.setText(_translate("Form", "alert"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "页签1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Tab 2"))
